version: '3.7'

services:

  alpine_chrome:
    image: zenika/alpine-chrome:latest
    container_name: gauguin-chrome-apline
    command: [chromium-browser, "--headless", "--disable-gpu", "--no-sandbox", "--remote-debugging-address=0.0.0.0", "--remote-debugging-port=9222"]
    ports:
      - 9222:9222
    restart: unless-stopped
    networks:
      - caddynet

  gin_gonic:
    container_name: gauguin-gin-gonic
    build:
      context: .
      dockerfile: ./Dockerfile
    links:
      - alpine_chrome
    depends_on:
      - alpine_chrome
    env_file:
      - .env
    ports:
      - 5491:5491
    volumes:
      - ./:/app
    restart: always
    networks:
      - caddynet

  caddy:
    image: abiosoft/caddy
    container_name: gauguin-caddy
    cap_add:
      - CAP_NET_BIND_SERVICE
    ports:
      - 8181:8181
    expose:
      - '8181'
    links:
      - gin_gonic
    depends_on:
      - gin_gonic
      - alpine_chrome
    volumes:
      - ./Caddyfile:/etc/Caddyfile
    command: -conf /etc/Caddyfile
    restart: always
    networks:
      - caddynet

networks:
  caddynet:
    driver: bridge