version: '3.7'

services:

  alpine_chrome:
    image: zenika/alpine-chrome:latest
    container_name: gauguin-chrome-alpine
    command: [chromium-browser, "--headless", "--disable-gpu", "--no-sandbox", "--disable-dev-shm-usage", "--remote-debugging-address=0.0.0.0", "--remote-debugging-port=9222"]
    ports:
      - 9222:9222
    restart: unless-stopped
    networks:
      - gauguin_net

  gin_gonic:
    container_name: gauguin-gin-gonic
    image: docker.pkg.github.com/micheleriva/gauguin/server:v0.0.4
    links:
      - alpine_chrome
    depends_on:
      - alpine_chrome
    env_file:
      - .env
    ports:
      - 5491:5491
    expose:
      - '5491'
    volumes:
      - ./templates:/app/templates
      - ./gauguin.yaml:/app/gauguin.yaml
    restart: unless-stopped
    networks:
      - gauguin_net

networks:
  gauguin_net:
    driver: bridge